services:
  - type: web
    name: qa-training-lab
    runtime: node
    aptPackages:
      - python3
      - make
      - g++
    buildCommand: npm install && cd server && npm install && cd ../client && npm install --include=dev && npm run build
    startCommand: cd server && npm run seed && npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        syncFromProperty: false
        value: https://qa-training-lab.onrender.com
